
export const cities = [
    // { municipale: "", label: "Ville" },
    { municipale: "Ariana", label: "Ariana" },
    { municipale: "Ben Arous", label: "Ben Arous" },
    { municipale: "Ben Gardane", label: "Ben Gardane" },
    { municipale: "Bizerte", label: "Bizerte" },
    { municipale: "Béja", label: "Béja" },
    { municipale: "Djerba - Houmt Souk", label: "Djerba - Houmt Souk" },
    { municipale: "Djerba - Midoun", label: "Djerba - Midoun" },
    { municipale: "Douar Hicher", label: "Douar Hicher" },
    { municipale: "El Aïn", label: "El Aîn" },
    { municipale: "El Mourouj", label: "El Mourouj" },
    { municipale: "Ettadhamen", label: "Ettadhamen" },
    { municipale: "Fouchana", label: "Fouchana" },
    { municipale: "Gabès", label: "Gabès" },
    { municipale: "Gafsa", label: "Gafsa" },
    { municipale: "Hammam Sousse", label: "Hammam Sousse" },
    { municipale: "Hammamet", label: "Hammamet" },
    { municipale: "Jemmal", label: "Jemmal" },
    { municipale: "Jendouba", label: "Jendouba" },
    { municipale: "Kairouan", label: "Kairouan" },
    { municipale: "Kalâa Kebira", label: "Kalâa Kebira" },
    { municipale: "Kasserine", label: "Kasserine" },
    { municipale: "Ksar Hellal", label: "Ksar Hellal" },
    { municipale: "Kélibia", label: "Kélibia" },
    { municipale: "La Goulette", label: "La Goulette" },
    { municipale: "La Marsa", label: "La Marsa" },
    { municipale: "La Soukra", label: "La Soukra" },
    { municipale: "Le Bardo", label: "Le Bardo" },
    { municipale: "Le Kef", label: "Le Kef" },
    { municipale: "Le Kram", label: "Le Kram" },
    { municipale: "M'saken", label: "M'saken" },
    { municipale: "Mahdia", label: "Mahdia" },
    { municipale: "Menzel Bourguiba", label: "Menzel Bourguiba" },
    { municipale: "Mnihla", label: "Mnihla" },
    { municipale: "Mohamedia", label: "Mohamedia" },
    { municipale: "Moknine", label: "Moknine" },
    { municipale: "Monastir", label: "Monastir" },
    { municipale: "Médenine", label: "Médenine" },
    { municipale: "Nabeul", label: "Nabeul" },
    { municipale: "Oued Ellil", label: "Oued Ellil" },
    { municipale: "Radés", label: "Radés" },
    { municipale: "Raoued", label: "Raoued" },
    { municipale: "Sakiet Eddaïer", label: "Sakiet Eddaier" },
    { municipale: "Sakiet Ezzit", label: "Sakiet Ezzit" },
    { municipale: "Sfax", label: "Sfax" },
    { municipale: "Sidi Bouzid", label: "Sidi Bouzid" },
    { municipale: "Sidi Hassine", label: "Sidi Hassine" },
    { municipale: "Sousse", label: "Sousse" },
    { municipale: "Tataouine", label: "Tataouine" },
    { municipale: "Tunis", label: "Tunis" },
    { municipale: "Zarzis", label: "Zarzis" },
]